account/urls.py
from django.conf.urls import url
from django.urls import path, include
from .api import RegisterApi

app_name = 'account'

urlpatterns = [
    path('api/register', RegisterApi.as_view()),
]

authentication/urls.py
from django.urls import path
from authentication.views import login_request, register,logout_request

app_name = 'authentication'

urlpatterns = [
    path('login/', login_request, name='login'),
    path('logout/',logout_request, name='logout'),
    path('register/', register, name='register'),
]

grayspaceit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts.views import posts
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls', namespace='authentication')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('account/',include('account.urls', namespace='account')),
    path('', posts),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

posts/urls.py
from django.urls import path
from posts.views import post_details,posts

app_name = 'posts'

urlpatterns = [
    path('', posts, name='posts'),
    path('<int:post_id>', post_details, name='post_details'),
]

account/models.py
from django.db import models

# Create your models here.

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import ugettext_lazy as _
# Create your models here.

class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)



class MyUser(AbstractUser):
    username = None
    email = models.EmailField(max_length=40, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    #Specified that all objects are coming from CustomUserManager
    objects = CustomUserManager()

posts/models.py
from django.db import models

# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import MyUser

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    #email = forms.EmailField(max_length=40)
    #User._meta.get_field('username')._unique = False
    #USERNAME_FIELD = 'email'

    class Meta:
        model = MyUser
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
    
    def clean_email(self):
        data = self.cleaned_data['email']
        if MyUser.objects.filter(email=data).count()>0:
            raise forms.ValidationError("Already have a user registered with this email-address.")
        return data

account/views.py
from django.shortcuts import render

# Create your views here.

authentication/views.py
from django.http import Http404
from django.shortcuts import render, redirect
from authentication.forms import SignUpForm
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages

# LOGIN VIEW ENDPOINT

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in!")
                return redirect('/')
            else:
                messages.error(request, 'Invalid username or password!')
        else:
            messages.error(request, 'Invalid username or password!')
    form = AuthenticationForm()
    context = {'form':form}
    return render(request, 'login.html', context)

def logout_request(request):
    logout(request)
    messages.info(request, "You are logged out!")
    return redirect('/')


def register(request):

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()    
            return redirect('authentication:login')
    else:
        form = SignUpForm()

    return render(request, 'register.html', {'form':form})

posts/views.py
from django.shortcuts import render
from django.http import response
import requests
import json

# POSTS VIEW ENDPOINT
def posts(request):
    response = requests.get("https://jsonplaceholder.typicode.com/posts").json()
    #print('response:',response[0])
    context = {'response':response}
    return render(request, 'blog-listing.html', context)

# POST DETAILS VIEW ENDPOINT
def post_details(request, post_id):
    response = requests.get("https://jsonplaceholder.typicode.com/posts/{}".format(post_id)).json()
    comments = requests.get("https://jsonplaceholder.typicode.com/posts/{}/comments".format(post_id)).json()
    #print('comments', comments)
    #print('response:',response[post_id ])
    #context = {'response':response[post_id-1]}
    context = {'response':response, 'comments':comments}
    return render(request, 'blog-post.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Modern Business - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static  'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static  'css/modern-business.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
	
        <a class="navbar-brand" href="/">Example Blog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
		{% if request.user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/posts">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">{{request.user}}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:logout' %}">Logout</a>
                </li>
		{% else %}
		<ul class="navbar-nav ml-auto">
		<li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'authentication:register' %}">Register</a>
                </li>
		</ul>
		{% endif %}
            </ul>
	
        </div>
    </div>
</nav>

{% block container %}
{% endblock container %}

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Gray Space It LTD 2020</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static  'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static  'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

<!-- Contact form JavaScript -->
<!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<script src="{% static  'js/jqBootstrapValidation.js'%}"></script>
<script src="{% static  'js/contact_me.js'%}"></script>

</body>

</html>"

templates/blog-listing.html
{% extends 'base.html' %}

{% block container %}
  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Blog Home Two
      <small>Subheading</small>
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active">Blog Home 2</li>
    </ol>

    <!-- Blog Post -->
    {% for data in response %}
    <div class="card mb-4">
      <div class="card-body">
        <div class="row">
          <div class="col-lg-6">
            <a href="#">
              <img class="img-fluid rounded" src="http://placehold.it/750x300" alt="">
            </a>
          </div>
          
          <div class="col-lg-6">
            <h2 class="card-title">{{data.title}}</h2>
            
            <p class="card-text">{{data.body}}</p>
            <a href="{% url 'posts:post_details' data.id %}" class="btn btn-primary">Read More &rarr;</a>
          </div>
          
        </div>
      </div>
      <div class="card-footer text-muted">
        Posted on January 1, 2017 by
        <a href="#">Start Bootstrap</a>
      </div>
    </div>
    {% endfor %}
    <!-- Pagination -->
    <ul class="pagination justify-content-center mb-4">
      <li class="page-item">
        <a class="page-link" href="#">&larr; Older</a>
      </li>
      <li class="page-item disabled">
        <a class="page-link" href="#">Newer &rarr;</a>
      </li>
    </ul>

  </div>
  <!-- /.container -->
{% endblock container %}

templates/blog-post.html
{% extends 'base.html' %}

{% block container %}

  <!-- Page Content -->
  
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">{{response.title}}
    </h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">Home</a>
      </li>
      <li class="breadcrumb-item active">Blog Home 2</li>
    </ol>

    <div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Preview Image -->
        <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">

        <hr>

        <!-- Date/Time -->
        <p>Posted on January 1, 2017 at 12:00 PM</p>

        <hr>

        <!-- Post Content -->
        <p class="lead">{{response.body}}</p>
        <hr>
        

        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Leave a Comment:</h5>
          <div class="card-body">
            <form>
              <div class="form-group">
                <textarea class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
          </div>
        </div>

        <!-- Single Comment -->
        {% for comment in comments %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">{{comment.name}}</h5>
            <h6 class="mt-0">{{comment.email}}</h6>
            <p class="mt-0">{{comment.body}}</p>
          </div>
        </div>
      {% endfor %}
        <!-- Comment with nested comments -->
        <div class="media mb-4">
          <div class="media-body">

            <div class="media mt-4">
              <div class="media-body">
              </div>
            </div>

            <div class="media mt-4">
              <div class="media-body">
              </div>
            </div>

          </div>
        </div>

      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Search Widget -->
        <div class="card mb-4">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="inpug-group-append">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>

        <!-- Categories Widget -->
        <div class="card my-4">
          <h5 class="card-header">Categories</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">Web Design</a>
                  </li>
                  <li>
                    <a href="#">HTML</a>
                  </li>
                  <li>
                    <a href="#">Freebies</a>
                  </li>
                </ul>
              </div>
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  <li>
                    <a href="#">JavaScript</a>
                  </li>
                  <li>
                    <a href="#">CSS</a>
                  </li>
                  <li>
                    <a href="#">Tutorials</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        <!-- Side Widget -->
        <div class="card my-4">
          <h5 class="card-header">Side Widget</h5>
          <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
          </div>
        </div>

      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

{% endblock container %}

templates/login.html
{% extends 'base.html' %}
 {% load crispy_forms_tags %}
{% block container %}
  <!-- Page Content -->
  <div class="container" style="min-height: 80vh;">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Login
      <small>Form</small>
    </h1>
    <ol class="breadcrumb">
      <li class="breadcrumb-item active">Login</li>
    </ol>
    <!-- Content Row -->
    <div class="row">
      <div class="col-lg-4 mb-4">
        <form method="POST">
        {% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
           <div class = 'alert alert-danger' role="alert">
              {{message}}
           </div>
        {% endif %}
    {% endfor %}
{% endif %}
          {% csrf_token %}
          {{form|crispy}}
          <!-- For success/fail messages -->
          <p>Don't have an account? Create one <a href="{% url 'authentication:register' %}">here</a></p>
          <button type="submit" class="btn btn-primary" id="login-btn">Login</button>
        </form>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
{% endblock container %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script> M.toast({html:"{{messages}}", classes: 'green rounded', displayLength:2000});</script>
        {% elif message.tags == 'info' %}
            <script> M.toast({html:"{{messages}}", classes: 'blue rounded', displayLength:2000});</script>
        {% elif message.tags == 'warning' %}
            <script> M.toast({html:"{{messages}}", classes: 'orange rounded', displayLength:2000});</script>
        {% elif message.tags == 'error' %}
            <script> M.toast({html:"{{messages}}", classes: 'red rounded', displayLength:2000});</script>
        {% endif %}
    {% endfor %}
{% endif %}

templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block container %}
    <!-- Page Content -->
    <div class="container" style="min-height: 80vh;">

        <!-- Page Heading/Breadcrumbs -->
        <h1 class="mt-4 mb-3">Register
            <small>Form</small>
        </h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item active">Register</li>
        </ol>
        <!-- Content Row -->

        <div class="row">
            <div class="col-lg-4 mb-4">
                <form method="POST" class=>
                    {% csrf_token %}
                    {{form|crispy}}
                    <button type="submit" class="btn btn-primary" id="login-btn">Register</button>
                </form>
            </div>
        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock container %}